add popup on button
alphym/portfolio pull request #9
Opened 2023-02-10 10:15 UTC by alphym

2023-02-10 11:20 UTC, Ibizugbe requested changes
Hi @alphym 👋👋, 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966](https://user-images.githubusercontent.com/64643995/218078691-5c1f044f-28e2-4fed-8c80-8c2221a19c21.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights✅

- [ ] Github flow has been used👍
- [ ] Linters are checked👍



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 11:20 UTC, Ibizugbe commented on index.html
> +    </div>
- [ ] Nice work implementing your modal👍👍 Bu don't forget it is a [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) that the content of your modal be generated dynamically😉😉 kindly go through the[ requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) and make the necessary changes🤗🤗

<img width="763" alt="pop__instruction" src="https://user-images.githubusercontent.com/64643995/218075309-852b69bc-1cf7-42a8-b37d-4a961b8deb44.png">

- [ ] Also, kindly avoid using inline styling as this is not a good CSS practice😉 kindly take all styles to an external stylesheet🤗
- [ ] I think your popup also looks a bit different from the given design👍👍 kindly confirm with the image below and make the necessary comparison🤗🤗

your popup(mobile)
<img width="311" alt="your_popup mobile" src="https://user-images.githubusercontent.com/64643995/218077031-2bb3608a-880a-4ed1-910c-7f352e6fceb2.png">

design
<img width="189" alt="popup_desktop" src="https://user-images.githubusercontent.com/64643995/218077967-c0929ddc-0a03-4634-be1c-c47c3b33c552.png">

kindly take note of the spacings also😉😉

Same for your desktop version😉😉 take note of the spacings between each contents😉😉😉

2023-02-10 11:20 UTC, Ibizugbe commented on index.html
> +                    <button class="modal-mobile-see-pro">See Project</button>
You have done a good job on this milestone👍👍 Just a quick reminder that it is a [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) in this milestone that our project section is generated dynamically using the array of objects you have created in your script file😉😉😉 kindly go through the requirements and make the required change🤗🤗

<img width="763" alt="pop__instruction" src="https://user-images.githubusercontent.com/64643995/218076331-36d445cf-bd0d-4e3f-839a-e33f32faf078.png">

2023-02-10 11:20 UTC, Ibizugbe commented on script.js
> +};
Nice work implementing the objects👍👍 but I suggest this should be an array of objects so you can easily loop through it and render it dynamically😉😉 also kindly add the `technologies used` and `link to live version` for each objects as these are also part of the contents of the popup and project section😉😉😉

2023-02-10 19:34 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @alphym , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] [REQUIRED] You have not fixed all the issues raised by the previous reviewer. I encourage you to take a close look at this issue and find a solution for them. 
   - Dynamically display all projects from an array.
   - Dynamically display a modal popup of the correct project button clicked.
   - othe issues raised. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 17:40 UTC, Favourezeugwa requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @alphym  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close lady](https://user-images.githubusercontent.com/99246359/207367678-ef4e9b86-75b7-4d8e-b9b5-899f2e87c934.gif)

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 17:40 UTC, Favourezeugwa commented on index.html
> +            </div>
- As suggested by the previous reviewer and part of the project's requirement, you need to implement both your modal and project cards in javaScript. No content of the project card or modal should be in your html file. 🌸 
- You can move this entire modal code to your script.js file

2023-02-11 19:35 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @alphym, 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of GitHub flow ✔️

## Optional changes

- [ ] [Optional] Great effort working on the changes requested by the previous reviewers, you have done wonderfully well creating your project cards and modal pop-up dynamically, but it would have been great if you make use of the `array of an object` method in storing your data rather that the method you used
E.g

```JS
const project = [
  {
    title: 'Tonic',
    description:
            'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    image: './images/project_1.png',
    liveVersion: 'https://alphym.github.io/portfolio/',
    skills: ['html', 'css', 'js'],
    sourceCode: 'https://github.com/alphym/portfolio',
  },
  {
    title: 'Multi-Post Stories',
    description:
            'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    image: './images/project_image2.png',
    liveVersion: 'https://alphym.github.io/portfolio/',
    sourceCode: 'https://github.com/alphym/portfolio',
  },
]
```

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 19:39 UTC, merged